-- Migration: Inserir marcas mais famosas de carros e motos
-- Execute este script no Supabase SQL Editor

-- Marcas de Carros (order_index: 1-50)
INSERT INTO brands (name, type, active, order_index) VALUES
  ('Chevrolet', 'carro', true, 1),
  ('Fiat', 'carro', true, 2),
  ('Volkswagen', 'carro', true, 3),
  ('Ford', 'carro', true, 4),
  ('Toyota', 'carro', true, 5),
  ('Honda', 'carro', true, 6),
  ('Nissan', 'carro', true, 7),
  ('Hyundai', 'carro', true, 8),
  ('Renault', 'carro', true, 9),
  ('Peugeot', 'carro', true, 10),
  ('Citroën', 'carro', true, 11),
  ('Jeep', 'carro', true, 12),
  ('Mitsubishi', 'carro', true, 13),
  ('Kia', 'carro', true, 14),
  ('Chery', 'carro', true, 15),
  ('CAOA Chery', 'carro', true, 16),
  ('Troller', 'carro', true, 17),
  ('RAM', 'carro', true, 18),
  ('Audi', 'carro', true, 19),
  ('BMW', 'carro', true, 20),
  ('Mercedes-Benz', 'carro', true, 21),
  ('Volvo', 'carro', true, 22),
  ('Land Rover', 'carro', true, 23),
  ('Jaguar', 'carro', true, 24),
  ('Porsche', 'carro', true, 25),
  ('Subaru', 'carro', true, 26),
  ('Mazda', 'carro', true, 27),
  ('Suzuki', 'carro', true, 28),
  ('BYD', 'carro', true, 29),
  ('GWM', 'carro', true, 30),
  ('Foton', 'carro', true, 31),
  ('JAC', 'carro', true, 32),
  ('Lifan', 'carro', true, 33),
  ('Mini', 'carro', true, 34),
  ('Smart', 'carro', true, 35)
ON CONFLICT (name) DO NOTHING;

-- Marcas de Motos (order_index: 1-30)
INSERT INTO brands (name, type, active, order_index) VALUES
  ('Honda', 'moto', true, 1),
  ('Yamaha', 'moto', true, 2),
  ('Suzuki', 'moto', true, 3),
  ('Kawasaki', 'moto', true, 4),
  ('Dafra', 'moto', true, 5),
  ('Shineray', 'moto', true, 6),
  ('Kasinski', 'moto', true, 7),
  ('Bajaj', 'moto', true, 8),
  ('Royal Enfield', 'moto', true, 9),
  ('Triumph', 'moto', true, 10),
  ('Harley-Davidson', 'moto', true, 11),
  ('Ducati', 'moto', true, 12),
  ('KTM', 'moto', true, 13),
  ('BMW', 'moto', true, 14),
  ('Vespa', 'moto', true, 15),
  ('Piaggio', 'moto', true, 16),
  ('Benelli', 'moto', true, 17),
  ('MV Agusta', 'moto', true, 18),
  ('Aprilia', 'moto', true, 19),
  ('Moto Guzzi', 'moto', true, 20),
  ('Husqvarna', 'moto', true, 21),
  ('CFMoto', 'moto', true, 22),
  ('Zontes', 'moto', true, 23),
  ('Lifan', 'moto', true, 24),
  ('Jinlun', 'moto', true, 25),
  ('Intruder', 'moto', true, 26),
  ('Voge', 'moto', true, 27),
  ('Mondial', 'moto', true, 28),
  ('Hero', 'moto', true, 29),
  ('SYM', 'moto', true, 30)
ON CONFLICT (name) DO NOTHING;

